Automation scripts update

diff --git a/scripts/helper_utils b/scripts/helper_utils
--- a/scripts/helper_utils
+++ b/scripts/helper_utils
@@ -3,32 +3,38 @@
 ### Dammavalam, Srirangam
 ### 20-OCT-2022
 
+#-------------------------
+C_RESET='\033[0m'
+C_RED='\033[0;31m'
+C_GREEN='\033[0;32m'
+C_BLUE='\033[0;34m'
+C_YELLOW='\033[1;33m'
+
 #---------------------------------------------
 # get_val function to get value of a variable
 # get_val <var>
 #---------------------------------------------
 get_val() {
-   _var1=$1
-   echo ${!_var1}
+  _var1=$1
+  echo ${!_var1}
 }
 
 #-------------------------------------------------------
-# wait_for_event function to display wait/progress bar
+# wait_for_seconds function to display wait/progress bar
 # while waiting for a process or event to be completed
-# wait_for_event <wait_seconds>
+# wait_for_seconds <wait_seconds>
 #-------------------------------------------------------
-wait_for_event() {
+wait_for_seconds() {
   _wait_sec=$1
   _cur_sec=1
   #_pchar="▇"
   _pchar="#"
   _pstr="["
   #for __sec__ in $(seq 1 $_wait_sec); do _pstr=$(echo "${_pstr}."); done
-  for ((_sec=1; _sec<=$_wait_sec; _sec++)); do _pstr=$(echo "${_pstr}."); done
+  for ((_sec = 1; _sec <= $_wait_sec; _sec++)); do _pstr=$(echo "${_pstr}."); done
   _pstr=$(echo "${_pstr}]")
   echo -ne "$_pstr\r["
-  while [ $_cur_sec -le $_wait_sec ];
-  do
+  while [ $_cur_sec -le $_wait_sec ]; do
     echo -n "$_pchar"
     sleep 1
     let _cur_sec++
@@ -36,3 +42,99 @@ wait_for_event() {
   echo
 }
 
+wait_for_process() {
+  pid_to_poll=$1
+  pbar_str="#"
+  echo -ne "\r"
+  until [ $(ps -p $pid_to_poll | grep -c $pid_to_poll) -eq 0 ]; do
+    echo -n "${pbar_str}"
+    sleep 1
+  done
+  echo ""
+}
+
+wait_for_file() {
+  file_to_check=$1
+  pbar_str="#"
+  echo -ne "\r"
+  until [ -f "$file_to_check" ]; do
+    echo -n "${pbar_str}"
+    sleep 1
+  done
+  echo ""
+}
+
+# println echos string
+function println() {
+  echo -e "$1"
+}
+
+# errorln echos in red color
+function errorln() {
+  println "${C_RED}${1}${C_RESET}"
+}
+
+# successln echos in green color
+function successln() {
+  println "${C_GREEN}${1}${C_RESET}"
+}
+
+# infoln echos in blue color
+function infoln() {
+  println "${C_BLUE}${1}${C_RESET}"
+}
+
+# warnln echos in yellow color
+function warnln() {
+  println "${C_YELLOW}${1}${C_RESET}"
+}
+
+# fatalln echos in red color and exits with fail status
+function fatalln() {
+  errorln "$1"
+  exit 1
+}
+
+export -f errorln
+export -f successln
+export -f infoln
+export -f warnln
+
+verify_result() {
+  if [ $1 -ne 0 ]; then
+    fatalln "$2"
+  fi
+}
+
+check_pre_reqs() {
+  jq --version >/dev/null 2>&1
+
+  if [[ $? -ne 0 ]]; then
+    errorln "jq command not found..."
+    exit 1
+  fi
+}
+
+print_header() {
+  max_len=40
+  for n in "$@"; do [[ ${#n} -gt $max_len ]] && { max_len=${#n}; }; done
+  echo -ne "+"
+  for n in $(seq 1 $((max_len + 2))); do echo -ne "-"; done
+  echo -ne "+\n"
+  printf "| %-${max_len}s |\n" "$(date)"
+  printf "| %-${max_len}s |\n" " "
+  printf "|$(tput bold) %-${max_len}s $(tput sgr0)|\n" "$@"
+  echo -ne "+"
+  for n in $(seq 1 $((max_len + 2))); do echo -ne "-"; done
+  echo -ne "+\n"
+}
+
+parse_template() {
+  _template_file=$1
+  _output_file=$2
+
+  eval "cat <<EOF
+$(cat $_template_file)
+EOF
+" >>$_output_file
+}
diff --git a/scripts/set_env b/scripts/set_env
--- a/scripts/set_env
+++ b/scripts/set_env
@@ -3,20 +3,43 @@
 ### Dammavalam, Srirangam
 ### 01-JUN-2021
 
-[[ "${0}" = "-bash" ]] && { __script_dir__=${PWD}; } || { __script_dir__=$(dirname $0); }
-__conf_file__=${__script_dir__}/../network.conf
-__helper_utils__=${__script_dir__}/../scripts/helper_utils
-if [ ! -f ${__helper_utils__} ]; then echo "${__helper_utils__} file NOT found. Exiting ..."; return; fi
-. ${__helper_utils__}
-if [ $# -eq 0 ]; then
-    if [ ! -f ${__conf_file__} ]; then echo "${__conf_file__} file NOT found. Exiting ..."; return; fi
+#[[ "${0}" = "-bash" ]] && { __script_dir__=${PWD}; } || { __script_dir__=$(dirname $0); }
+__script_dir__=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
+
+## import/source conf file
+if [ -z "$HLF_CONF_FILE" ]; then
+    echo "'HLF_CONF_FILE' env var is not defined, using default file 'network.conf'"
+    __conf_file__=${__script_dir__}/../network.conf
+    if [ ! -f ${__conf_file__} ]; then
+        echo "${__conf_file__} file NOT found. Exiting ..."
+        return
+    fi
     . ${__conf_file__}
 else
-    __vars_file__=$1
-    if [ ! -f ${__vars_file__} ]; then echo "${__vars_file__} NOT found. Exiting ..."; return; fi
+    __vars_file__=$HLF_CONF_FILE
+    if [ ! -f ${__vars_file__} ]; then
+        echo "${__vars_file__} NOT found. Exiting ..."
+        return
+    fi
     . ${__vars_file__}
 fi
 
+## import/source helper_utils
+__helper_utils__=${__script_dir__}/helper_utils
+if [ ! -f ${__helper_utils__} ]; then
+    echo "${__helper_utils__} file NOT found. Exiting ..."
+    return
+fi
+. ${__helper_utils__}
+
+## Add to PATH
+export PATH=$PATH:${HLF_HOME}/bin
+
+## Switch CWD
+#cd ${HLF_HOME}
+
+export COMPOSE_PROJECT_NAME=net
+export NETWORK_DIR=${HLF_HOME}/mytest-network
 export FABRIC_CFG_PATH=${HLF_HOME}/config/
 
 export CORE_PEER_LOCALMSPID=${ORG_MSPID}
@@ -26,3 +49,6 @@ export CORE_PEER_TLS_ENABLED=true
 export CORE_PEER_TLS_ROOTCERT_FILE=$HLF_NETWORK_DIR/organizations/peerOrganizations/${ORG_NAME}/peers/${HLF_ORG_PEER1_ID}/tls/tlscacerts/tls-cacert.pem
 export ORDERER_CA=$HLF_NETWORK_DIR/organizations/ordererOrganizations/${HLF_ORDR_ORG_NAME}/msp/tlscacerts/tls-cacert.pem
 export ORDERER_ADDRESS=${HLF_ORDR_HOST}:${HLF_ORDR_PORT}
+
+## IPFS
+export IPFS_CLUSTER_SECRET=64d0be1e4a0a2713bda4aa5be8462ae6103eb6ac77e760ce6f9d11b2bb6faff8
